# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: 'Main'
    pool:
      vmImage: 'Ubuntu 16.04'
    timeoutInMinutes: 0

    steps:
    - script: make
      displayName: 'Build Runtime'

    - task: CopyFiles@2
      inputs:
        contents: 'jdk_*.tar.gz'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'RaspbianJDK'
